### ISSUE TITLE
Nehemoth Audio

### ISSUE THREAD

**Issue by Ravinpanachi** [Sonmok14/FromTheShadows#15]
I love the mod. However, why is the audio of the nehemoth stomping around so loud. I understand if you were close to the monster. But if Im 50 blocks above the monster when hes deep inside a cave. I don't really think there is a reason i should be hearing his stomping that loud from when Im standing next to it compared to me being so far away. Is there a way to lower just that mobs audio or make the audio perspection for this stomping noise to actually work like other mobs audio?

**Comment by Sonmok14** [comment]
Does it happen in the latest version? I forgot to write the changelog, but it is fixed in the latest version
If it's not the latest version, I recommend you try the latest version
https://www.curseforge.com/minecraft/mc-mods/from-the-shadows/files
