### ISSUE TITLE
Woah, what happened?

### ISSUE THREAD

**Issue by TheRealGCZ** [Sonmok14/FromTheShadows#25]
Mod pages for From The Shadows were pulled off of both CurseForge and Modrinth. Just a heads up for everyone, and an expression of confusion towards Sonmok14...

What happened?

**Comment by codec-d** [comment]
I think license issues

**Comment by Sonmok14** [comment]
I'm very tired of developing mod
Tbh this doesn't suit me
I want to stop developing and focus on the work that suits me

**Comment by TheRealGCZ** [comment]
That makes sense. You do you, stay happy and safe out there. Whatever keeps your boat floating is what's most important.
