### ISSUE TITLE
crash with the nehemoth when encountering a train contraption from the create mod +

### ISSUE THREAD

**Issue by azuichh** [Sonmok14/FromTheShadows#3]
hello, i seem to crash

**Comment by azuichh** [comment]
fuck, sended it by accident, here is the crashlog 
[crash-2023-08-02_19.38.29-client.txt](https://github.com/Sonmok14/FromTheShadows/files/12243240/crash-2023-08-02_19.38.29-client.txt)

**Comment by Sonmok14** [comment]
Now you can hit Nehemoth by train

https://github.com/Sonmok14/FromTheShadows/assets/140219329/d8177699-4fa6-47a7-83d6-b20551b60f59

I don't play create very well, but I think it's fixed for now. fixed version will be uploaded either today or tomorrow.
Don't bother Nehemoth too much hehe

**Comment by azuichh** [comment]
i was just experimenting with my drilling train, i play with create a lot and decided it would be comic to make a big mining train, i simply forgot that this gave a verrrrrry large flat area where nehemoth could perfectly spawn, and upon testing i usualy have to go to the station often, that where i discovered that nehemoth weren't train friendly
