### ISSUE TITLE
create potato cannon crash when shooting nehemoth 

### ISSUE THREAD

**Issue by azuichh** [Sonmok14/FromTheShadows#4]
hello again,sorry to bother you with a issue with create again but i found out that nehemoth not only dislike train but they also dislike eating their vegie, granted i shoot the veggie at high speed with a literal potato cannon they will still hate it and cause my game to crash 

here is the crash log 
[crash-2023-08-05_19.03.17-server.txt](https://github.com/Sonmok14/FromTheShadows/files/12267722/crash-2023-08-05_19.03.17-server.txt)

**Comment by Sonmok14** [comment]
Try the latest version
And I think it would be better if you could tell me what vegetables you fired with a potato cannon
https://www.curseforge.com/minecraft/mc-mods/from-the-shadows/files/4679179

**Comment by azuichh** [comment]
it's indeed working, impressive work man, keep up with your mod it's really a nice mod
